name: Build & Release Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo'yu checkout et
      - uses: actions/checkout@v4

      # 2️⃣ Java 17 kur
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Gradle kur
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4️⃣ Android SDK kur
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # 5️⃣ Release APK build
      - name: Build Release APK
        run: gradle clean assembleRelease
        
      - name: List release folder
        run: ls -l app/build/outputs/apk/release/
  
      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-debug.apk app/build/outputs/apk/release/Yandoor.apk

      - name: Upload Release APK
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: "Yandoor APK"
          tag: ${{ github.ref_name }}
          artifacts: app/build/outputs/apk/release/Yandoor.apk
          draft: false
          prerelease: false
