name: Build & Release Signed Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # keystore
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
          -keystore yandoor.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -alias yandoor_key \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=Yandoor, OU=App, O=Yandoor, L=City, S=State, C=TR"

      # build
      - name: Build Signed Release APK
        run: |
          gradle clean assembleRelease \
          -Pandroid.injected.signing.store.file=$PWD/yandoor.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=yandoor_key \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Yandoor.apk

      # draft new release
      - name: Upload Release APK
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Yandoor APK"
          tag: ${{ github.ref_name }}
          artifacts: app/build/outputs/apk/release/Yandoor.apk
          allowUpdates: true
          draft: false
          prerelease: false
